#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 17, 2020 11:00:36 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import simpleGUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    simpleGUI_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    simpleGUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("662x451+506+455")
        top.minsize(120, 1)
        top.maxsize(2564, 1421)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.entry_width = tk.Entry(top)
        self.entry_width.place(relx=0.298, rely=0.222, height=21, relwidth=0.112)

        self.entry_width.configure(background="white")
        self.entry_width.configure(cursor="fleur")
        self.entry_width.configure(disabledforeground="#a3a3a3")
        self.entry_width.configure(font="TkFixedFont")
        self.entry_width.configure(foreground="#000000")
        self.entry_width.configure(insertbackground="black")

        self.message_width = tk.Message(top)
        self.message_width.place(relx=0.118, rely=0.222, relheight=0.053
                , relwidth=0.077)
        self.message_width.configure(background="#d9d9d9")
        self.message_width.configure(foreground="#000000")
        self.message_width.configure(highlightbackground="#d9d9d9")
        self.message_width.configure(highlightcolor="black")
        self.message_width.configure(text='''Width''')
        self.message_width.configure(width=46)

        self.message_height = tk.Message(top)
        self.message_height.place(relx=0.116, rely=0.288, relheight=0.053
                , relwidth=0.077)
        self.message_height.configure(background="#d9d9d9")
        self.message_height.configure(foreground="#000000")
        self.message_height.configure(highlightbackground="#d9d9d9")
        self.message_height.configure(highlightcolor="black")
        self.message_height.configure(text='''Height''')
        self.message_height.configure(width=70)

        self.entry_height = tk.Entry(top)
        self.entry_height.place(relx=0.298, rely=0.288, height=21
                , relwidth=0.112)
        self.entry_height.configure(background="white")
        self.entry_height.configure(disabledforeground="#a3a3a3")
        self.entry_height.configure(font="TkFixedFont")
        self.entry_height.configure(foreground="#000000")
        self.entry_height.configure(insertbackground="black")

        self.button_generate = tk.Button(top)
        self.button_generate.place(relx=0.298, rely=0.355, height=26, width=78)
        self.button_generate.configure(activebackground="#ececec")
        self.button_generate.configure(activeforeground="#000000")
        self.button_generate.configure(background="#d9d9d9")
        self.button_generate.configure(command=simpleGUI_support.Generate)
        self.button_generate.configure(cursor="fleur")
        self.button_generate.configure(disabledforeground="#a3a3a3")
        self.button_generate.configure(foreground="#000000")
        self.button_generate.configure(highlightbackground="#d9d9d9")
        self.button_generate.configure(highlightcolor="black")
        self.button_generate.configure(pady="0")
        self.button_generate.configure(text='''GENERATE''')

if __name__ == '__main__':
    vp_start_gui()


